name: Ruff

on: [push, pull_request]

jobs:
  build:

    name: Python ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
            python-version: ${{ matrix.python-version }}

      - name: Ruff
        uses: chartboost/ruff-action@v1
